server:
  port: 8888
app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/users/**
          filters:
            - StripPrefix=2
            # có tác dụng http://localhost:8080/identity/** thì ta thêm 1 giá trị nào đó vào localhost:8080/**/identity/ ko bị sao

        - id: profile-service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/profile/**
          filters:
            - StripPrefix=2